model:
  users:
    maximum_name: 50
    maximum_email: 255
    minimum_password: 6
    time: 2
  microposts:
    size_post: 140
    size_bit: 5
view:
  users:
    size: 50
helpers:
  size_gravatar: 80
controller:
  user_controller:
    size_page: 20
microposts:
  size_img: 50
uploader:
  size_img : 400
